### ISSUE TITLE
Please fix the warning

### ISSUE THREAD

**Issue by tonjac** [AlvaroFranco/AFDropdownNotification#1]
Please fix the runtime warning:
"Multiple gravity behavior per animator is undefined and may assert in the future"

**Comment by GreyEcologist** [comment]
Hey @AlvaroFranco so I was getting the same issue, it turns out an UIDynamicAnimator can only have one UIGravity associated with it, so in the dismissWithGravityAnimation:(BOOL), before add the removal behavior, you must call [_animator removeAllBehaviors];

You have it after in the dispatch, but it's also necessary before adding a behavior to _animator. Hope that helps.

```

-(void)dismissWithGravityAnimation:(BOOL)animation {

    if (animation) {

        [_animator removeAllBehaviors]; // line that solves the issue
        UIGravityBehavior *gravity = [[UIGravityBehavior alloc] initWithItems:@[_notificationView]];
        gravity.gravityDirection = CGVectorMake(0, -1.5);
        [_animator addBehavior:gravity];
        ....

```
